#!/usr/bin/env python3
"""Render the SPIR-V grammar tables consumed by Vpipe.SpirV.Generated."""

import json
import pathlib
import sys


HEADER = """-- This file is generated by tools/generate-spirv/generate.py.  Do not edit.\n-- Source: SPIRV-Headers ad9184e76a66b1001c29db9b0a3e87f646c64de0\n-- Grammar git blob: 22f5fe9c76f1fb292e93629d316ac6ff69fd193f (SPIR-V 1.6 rev. 4).\n{-# OPTIONS_HADDOCK hide #-}\n\nmodule Vpipe.SpirV.Generated where\n\nimport Data.Maybe (fromMaybe)\nimport Data.Word (Word16, Word32)\n\nopcode :: String -> Word16\nopcode name = fromMaybe (error (\"unknown SPIR-V opcode: \" ++ name)) (lookup name opcodeTable)\n\nenumerant :: String -> String -> Word32\nenumerant kind name = case lookup kind enumerantTables >>= lookup name of\n  Just value -> value\n  Nothing -> error (\"unknown SPIR-V enumerant: \" ++ kind ++ \".\" ++ name)\n\n"""

ALIASES = {
    "opName": ("Word16", 'opcode "OpName"'), "opMemberName": ("Word16", 'opcode "OpMemberName"'),
    "opExtension": ("Word16", 'opcode "OpExtension"'), "opExtInstImport": ("Word16", 'opcode "OpExtInstImport"'),
    "opMemoryModel": ("Word16", 'opcode "OpMemoryModel"'), "opEntryPoint": ("Word16", 'opcode "OpEntryPoint"'), "opExecutionMode": ("Word16", 'opcode "OpExecutionMode"'),
    "opCapability": ("Word16", 'opcode "OpCapability"'), "opTypeVoid": ("Word16", 'opcode "OpTypeVoid"'), "opTypeBool": ("Word16", 'opcode "OpTypeBool"'), "opTypeInt": ("Word16", 'opcode "OpTypeInt"'), "opTypeFloat": ("Word16", 'opcode "OpTypeFloat"'), "opTypeVector": ("Word16", 'opcode "OpTypeVector"'), "opTypeMatrix": ("Word16", 'opcode "OpTypeMatrix"'), "opTypeArray": ("Word16", 'opcode "OpTypeArray"'), "opTypeRuntimeArray": ("Word16", 'opcode "OpTypeRuntimeArray"'), "opTypeStruct": ("Word16", 'opcode "OpTypeStruct"'), "opTypePointer": ("Word16", 'opcode "OpTypePointer"'), "opTypeFunction": ("Word16", 'opcode "OpTypeFunction"'),
    "opConstantTrue": ("Word16", 'opcode "OpConstantTrue"'), "opConstantFalse": ("Word16", 'opcode "OpConstantFalse"'), "opConstant": ("Word16", 'opcode "OpConstant"'), "opConstantComposite": ("Word16", 'opcode "OpConstantComposite"'), "opVariable": ("Word16", 'opcode "OpVariable"'), "opLoad": ("Word16", 'opcode "OpLoad"'), "opStore": ("Word16", 'opcode "OpStore"'), "opDecorate": ("Word16", 'opcode "OpDecorate"'), "opMemberDecorate": ("Word16", 'opcode "OpMemberDecorate"'), "opFunction": ("Word16", 'opcode "OpFunction"'), "opFunctionEnd": ("Word16", 'opcode "OpFunctionEnd"'), "opLabel": ("Word16", 'opcode "OpLabel"'), "opReturn": ("Word16", 'opcode "OpReturn"'),
    "capabilityShader": ("Word32", 'enumerant "Capability" "Shader"'), "addressingModelLogical": ("Word32", 'enumerant "AddressingModel" "Logical"'), "memoryModelGLSL450": ("Word32", 'enumerant "MemoryModel" "GLSL450"'),
    "executionModelVertex": ("Word32", 'enumerant "ExecutionModel" "Vertex"'), "executionModelFragment": ("Word32", 'enumerant "ExecutionModel" "Fragment"'), "executionModelGLCompute": ("Word32", 'enumerant "ExecutionModel" "GLCompute"'), "executionModeOriginUpperLeft": ("Word32", 'enumerant "ExecutionMode" "OriginUpperLeft"'), "executionModeLocalSize": ("Word32", 'enumerant "ExecutionMode" "LocalSize"'), "storageClassOutput": ("Word32", 'enumerant "StorageClass" "Output"'),
    "decorationBlock": ("Word32", 'enumerant "Decoration" "Block"'), "decorationBuiltIn": ("Word32", 'enumerant "Decoration" "BuiltIn"'), "decorationLocation": ("Word32", 'enumerant "Decoration" "Location"'), "decorationComponent": ("Word32", 'enumerant "Decoration" "Component"'), "decorationOffset": ("Word32", 'enumerant "Decoration" "Offset"'), "decorationArrayStride": ("Word32", 'enumerant "Decoration" "ArrayStride"'), "decorationMatrixStride": ("Word32", 'enumerant "Decoration" "MatrixStride"'), "decorationColMajor": ("Word32", 'enumerant "Decoration" "ColMajor"'), "decorationDescriptorSet": ("Word32", 'enumerant "Decoration" "DescriptorSet"'), "decorationBinding": ("Word32", 'enumerant "Decoration" "Binding"'), "builtInPosition": ("Word32", 'enumerant "BuiltIn" "Position"'),
}


def pairs(values, name_key, value_key):
    return [(entry[name_key], int(str(entry[value_key]), 0)) for entry in values if name_key in entry and value_key in entry]


def render_pairs(items, indent="  "):
    return "\n".join(f'{indent}({json.dumps(name)}, {value})' + ("," if index + 1 < len(items) else "") for index, (name, value) in enumerate(items))


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate.py GRAMMAR OUTPUT")
    grammar = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
    instructions = pairs(grammar["instructions"], "opname", "opcode")
    enumerants = []
    for operand_kind in grammar["operand_kinds"]:
        values = operand_kind.get("enumerants")
        if values:
            enumerants.append((operand_kind["kind"], pairs(values, "enumerant", "value")))

    output = [HEADER, "opcodeTable :: [(String, Word16)]\nopcodeTable =\n  [", render_pairs(instructions), "  ]\n\n", "enumerantTables :: [(String, [(String, Word32)])]\nenumerantTables =\n  ["]
    for table_index, (kind, values) in enumerate(enumerants):
        suffix = "," if table_index + 1 < len(enumerants) else ""
        output.extend([f"    ({json.dumps(kind)},\n      [", render_pairs(values, "        "), f"      ]){suffix}"])
    output.append("  ]\n\n")
    for name, (type_name, expression) in ALIASES.items():
        output.append(f"{name} :: {type_name}\n{name} = {expression}\n")
    pathlib.Path(sys.argv[2]).write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
